project_id = "urczlhjnztiaxdsatueu"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-event-invitations]
verify_jwt = true

[functions.send-event-rejection]
verify_jwt = true

[functions.create-member]
verify_jwt = true

[functions.purge-member]
verify_jwt = true