project_id = "urczlhjnztiaxdsatueu"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-individual-invitation]
verify_jwt = true

[functions.send-event-invitations]
verify_jwt = true

[functions.send-event-rejection]
verify_jwt = true